#! /bin/bash
#
# motion 4.5	
# Start the motion detection .
#

NAME=motion
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/motion
PIDFILE=/run/motion/motion.pid


trap "" 1
export LANG=C
export PATH

test -f $DAEMON || exit 0


case "$1" in
  start)
    echo "Starting motion detection : $NAME"
    # start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON --chuid motion --umask 002
    start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON --chuid www-data --umask 002
    ;;

  stop)
    echo "Stopping motion detection : $NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --oknodo --exec $DAEMON --retry 30

    # If the process is still running, kill it
    if /usr/bin/ps ax | grep "/usr/bin/motion" | grep -v "grep"; then
        echo "Force stopping motion detection (kill)"
        killall motion
    fi
    ;;

  status)
    echo "Status motion detection : $NAME"
    if (test -f $PIDFILE); then
        echo -n "Running process for $NAME : "
    	pidof $NAME  
    else
    	echo "Stopped"
    fi
    ;;
    
  reload-config)
    echo "Reloading $NAME configuration"
    start-stop-daemon --stop --pidfile $PIDFILE --signal HUP --exec $DAEMON
    ;;

  restart-motion)
    echo "Restarting $NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --oknodo --exec $DAEMON --retry 30
    # start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON --chuid motion --umask 002
    start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON --chuid www-data --umask 002
    ;;

  restart)
    $0 restart-motion
    exit $?
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|status|reload-config|restart}"
    exit 1
    ;;
esac

if [ $? == 0 ]; then
	echo .
	exit 0
else
	echo failed
	exit 1
fi