#!/bin/bash

DATA_DIR="/var/lib/motionui"
SERVICE="$DATA_DIR/tools/service/motionui-service"

# Create/recreate symlink for motionui script
rm -f "/usr/bin/motionui"
ln -sf /var/lib/motionui/tools/motionui /usr/bin/motionui

# Quit if systemd is not installed (e.g. github runners)
if [ ! -f "/usr/bin/systemd" ];then
    exit
fi

# Install service as a systemd service
# Copy files and restart service to take any changes into account

# First stop motionui service if started
if systemctl is-active --quiet motionui;then
    systemctl stop --quiet motionui
fi

# Copy systemd service template 
\cp "/var/lib/motionui/tools/service/motionui.systemd.template" "/lib/systemd/system/motionui.service"

# Enable service script by creating a symlink
ln -sf /lib/systemd/system/motionui.service /etc/systemd/system/motionui.service
chmod 550 "$SERVICE"
systemctl daemon-reload

# Start motionui
systemctl start --quiet motionui

# Set permissions
/usr/bin/motionui --assume-yes --permissions

# Set up motion captures dir
mkdir -p /var/lib/motion
chown motion:motion /var/lib/motion
chmod 775 /var/lib/motion