#!/usr/bin/env bash
set -u

EVENTS_DIR="/var/lib/motionui/events"
DAY=$(LC_ALL="en_EN.UTF-8" date +%A)
TIME=$(date +%H%M)
DATE_NOW=$(date +%Y-%m-%d)
TIME_NOW=$(date +%H:%M)
REGISTER_EVENT_ID=""
EVENT_ID=""
REGISTER_EVENT_ID=""
EVENT_FILE=""
CAMERA_ID=""
CAMERA_NAME=""

function addEvent
{
    if [ -z "$CAMERA_ID" ];then
        echo "Error trying to create event: you must specify camera Id (--cam-id) to register event"
        exit
    fi

    EVENT_CONTENT="ID=$REGISTER_EVENT_ID\n"
    EVENT_CONTENT+="STATUS=new\n"
    EVENT_CONTENT+="DATE_START=$DATE_NOW\n"
    EVENT_CONTENT+="TIME_START=$TIME_NOW\n"
    EVENT_CONTENT+="CAMERA_ID=$CAMERA_ID\n"
    EVENT_CONTENT+="CAMERA_NAME=$CAMERA_NAME"

    echo -e "$EVENT_CONTENT" > "$EVENTS_DIR/${CAMERA_ID}-event-${REGISTER_EVENT_ID}"
    chmod 660 "$EVENTS_DIR/${CAMERA_ID}-event-${REGISTER_EVENT_ID}"
}

function addEventFile
{
    if [ -z "$CAMERA_ID" ];then
        echo "Error trying to add event file: you must specify camera Id (--cam-id) to register event"
        exit
    fi

    if [ -z "$EVENT_ID" ];then
        echo "Error trying to add event file: Event Id must be specified when using --file parameter."
        return
    fi

    if [ ! -f "$EVENTS_DIR/${CAMERA_ID}-event-${EVENT_ID}" ];then
        echo "Error trying to add event file: Event file '$EVENTS_DIR/${CAMERA_ID}-event-${EVENT_ID}' not found."
        return
    fi

    echo "FILE=$EVENT_FILE" >> "$EVENTS_DIR/${CAMERA_ID}-event-${EVENT_ID}"
}

function endEvent
{
    if [ -z "$CAMERA_ID" ];then
        echo "Error trying to end event: you must specify camera Id (--cam-id) to end event"
        exit
    fi

    if [ -z "$EVENT_ID" ];then
        echo "Error trying to end event: Event Id must be specified when using --end-event parameter."
        return
    fi

    if [ ! -f "$EVENTS_DIR/${CAMERA_ID}-event-${EVENT_ID}" ];then
        echo "Error trying to end event: Event file '$EVENTS_DIR/${CAMERA_ID}-event-${EVENT_ID}' not found."
        return
    fi

    # Add end date and time for this event
    echo -e "DATE_END=${DATE_NOW}\nTIME_END=${TIME_NOW}" >> "$EVENTS_DIR/${CAMERA_ID}-event-${EVENT_ID}"
}

mkdir -p "$EVENTS_DIR"

while [ $# -ge 1 ];do
    case "$1" in
        -ci|--cam-id)
            CAMERA_ID="$2"
            shift
        ;;
        -cn|--cam-name)
            CAMERA_NAME="$2"
            shift
        ;;
        -re|--register-event)
            REGISTER_EVENT_ID="$2"
            addEvent
            exit
        ;;
        -e|--event)
            EVENT_ID="$2"
            shift
        ;;
        -ee|--end-event)
            EVENT_ID="$2"
            endEvent
            exit
        ;;
        -f|--file)
            EVENT_FILE="$2"
            addEventFile
            exit
        ;;
           *)
        echo "Unknown parameter : $1"
        ;;
    esac
    shift
done

exit