name: Publish Docker image

on:
  release:
    types: [ published ]

# Debug only
# on:
#   push:
#     branches: [ devel ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        # Debug only
        # with:
        #   ref: 'devel'

      - name: Retrieve motion-UI version
        run: |
          echo "VERSION=$(cat ${GITHUB_WORKSPACE}/www/version)" >> $GITHUB_ENV
          echo "Version: ${{ env.VERSION }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build the images
      - name: Build and push docker
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          # Debug only
          # push: true
          # tags: lbr38/motionui:${{ env.VERSION }}-test
          # platforms: linux/amd64,linux/i386,linux/arm/v7,linux/arm64

          # Production
          push: true
          tags: lbr38/motionui:latest, lbr38/motionui:${{ env.VERSION }}
          platforms: linux/amd64,linux/i386,linux/arm/v7,linux/arm64
      